#
# Author: Ayoub Chouak (a.chouak@protonmail.com)
# Brief:  Matrix build tests in Travis CI
#

sudo: required

services:
    - docker

env:
    - distribution: cern/slc6-base
      distribution_name: slc6-base
      version: latest
    - distribution: centos
      distribution_name: centos
      version: 7

before_install:
        - docker pull ${distribution}:${version}
        - docker build --no-cache --rm --file=travis/Dockerfile.${distribution_name}-${version} --tag=${distribution_name}-${version}:yampl-build travis'        - docker run -d --volume="${PWD}":/home/yampl/workdir ${distribution_name}-${version}:yampl-build > "${container_id}"
        - docker ps -a

script:
    - container_id=$(mktemp)
    - docker exec "$(cat ${container_id})" mkdir build_${container_id}; cd build_${container_dir}; cmake .. -DWITH_EXAMPLES=ON && sudo make
