#
# Author: Ayoub Chouak (a.chouak@protonmail.com)
# Brief:  Matrix build tests in Travis CI
#

sudo: required

services:
    - docker

env:
    - distribution: cern/slc6-base
      distribution_name: slc6-base
      version: latest
    - distribution: centos
      distribution_name: centos
      version: 7

before_install:
    - docker pull ${distribution}:${version}
    - docker build --file=travis/Dockerfile.${distribution_name}-${version} --tag=${distribution_name}-${version}:yampl-build travis

script:
    - container_id=$(mktemp)
    - docker run -d --volume="${PWD}":/yampl ${distribution_name}-${version}:yampl-build > "${container_id}"
    - docker ps -a
    - docker exec "$(cat ${container_id})" bash -c "echo Building YAMPL on Linux Kernel $(uname -r)..."
    - docker exec "$(cat ${container_id})" bash -c "cd /yampl; mkdir build; cd build; cmake .. -DWITH_EXAMPLES=ON && sudo make"
